apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/instance: odh-nim-operator-0.0.1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: opendatahub-nim-operator
    app.kubernetes.io/part-of: opendatahub-nim-operator
    app.kubernetes.io/version: 0.0.1
  name: odh-nim-operator-metrics-service
spec:
  ports:
  - name: metrics
    port: 8383
    protocol: TCP
    targetPort: 0
  selector:
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: opendatahub-nim-operator
status:
  loadBalancer: {}
