apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "nim.opendatahub.io/v1alpha1",
          "kind": "OdhNIMAccount",
          "metadata": {
            "name": "odh-nim-account",
            "namespace": "redhat-ods-applications"
          },
          "spec": {
            "secretRef": {
              "name": "odh-nim-access"
            }
          }
        },
        {
          "apiVersion": "nim.opendatahub.io/v1alpha1",
          "kind": "OdhNIMRuntime",
          "metadata": {
            "name": "odh-nim-runtime",
            "namespace": "nim-project"
          },
          "spec": {
            "inferenceServiceSpec": {
              "predictor": {
                "maxReplicas": 1,
                "minReplicas": 1,
                "model": {
                  "modelFormat": {
                    "name": "arctic-embed-l"
                  },
                  "name": "",
                  "resources": {
                    "limits": {
                      "cpu": "8",
                      "memory": "10Gi",
                      "nvidia.com/gpu": "1"
                    },
                    "requests": {
                      "cpu": "4",
                      "memory": "8Gi",
                      "nvidia.com/gpu": "1"
                    }
                  },
                  "runtime": "my-custom-serving"
                },
                "tolerations": [
                  {
                    "effect": "NoSchedule",
                    "key": "nvidia.com/gpu",
                    "operator": "Exists"
                  },
                  {
                    "effect": "NoSchedule",
                    "key": "odh-notebook",
                    "operator": "Exists"
                  }
                ]
              },
              "pvcSpec": {
                "accessModes": [
                  "ReadWriteOnce"
                ],
                "resources": {
                  "requests": {
                    "storage": "8Gi"
                  }
                },
                "selector": {
                  "matchExpressions": [
                    {
                      "key": "environment",
                      "operator": "In",
                      "values": [
                        "dev"
                      ]
                    }
                  ],
                  "matchLabels": {
                    "release": "stable"
                  }
                },
                "storageClassName": "slow",
                "volumeMode": "Filesystem"
              }
            },
            "odhNIMAccountRef": {
              "name": "odh-nim-app",
              "namespace": "redhat-ods-applications"
            }
          },
          "status": {
            "conditions": [
              {
                "lastTransitionTime": "2024-09-26T00:00:00Z",
                "reason": "PVCReconciledSuccessfully",
                "status": "True",
                "type": "PVCReconciled"
              },
              {
                "lastTransitionTime": "2024-09-26T00:00:00Z",
                "reason": "ImagePullSecretReconciledSuccessfully",
                "status": "True",
                "type": "ImagePullSecretReconciled"
              },
              {
                "lastTransitionTime": "2024-09-26T00:00:00Z",
                "reason": "NimSecretReconciledSuccessfully",
                "status": "True",
                "type": "NimSecretReconciled"
              },
              {
                "lastTransitionTime": "2024-09-26T00:00:00Z",
                "reason": "ServingRuntimeReconciledSuccessfully",
                "status": "True",
                "type": "ServingRuntimeReconciled"
              },
              {
                "lastTransitionTime": "2024-09-26T00:00:00Z",
                "reason": "InferenceServiceReconciledSuccessfully",
                "status": "True",
                "type": "InferenceReconciledCreation"
              }
            ],
            "imagePullSecretRef": {
              "name": "ngc-secret"
            },
            "inferenceServiceRef": {
              "name": "my-custom-serving"
            },
            "nimSecretRef": {
              "name": "nvidia-nim-secrets"
            },
            "pvcRef": {
              "name": "nim-pvc"
            },
            "servingRuntimeRef": {
              "name": "my-custom-serving"
            }
          }
        }
      ]
    capabilities: Basic Install
    createdAt: "2024-10-23T18:59:14Z"
    operators.operatorframework.io/builder: operator-sdk-v1.37.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
  name: odh-nim-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: OdhNIMAccount is used for adopting a NIM Account for Open Data
        Hub.
      displayName: ODH NIM Account
      kind: OdhNIMAccount
      name: odhnimaccounts.nim.opendatahub.io
      resources:
      - kind: ConfigMap
        name: ""
        version: v1
      - kind: Template
        name: ""
        version: template.openshift.io/v1
      statusDescriptors:
      - displayName: Conditions
        path: conditions
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes.conditions
      version: v1alpha1
    - description: OdhNIMRuntime is used for creating NIM Kserve-based deployment
        for Open Data Hub.
      displayName: ODH NIM Runtime
      kind: OdhNIMRuntime
      name: odhnimruntimes.nim.opendatahub.io
      resources:
      - kind: InferenceService
        name: ""
        version: serving.kserve.io/v1beta1
      - kind: ServingRuntime
        name: ""
        version: serving.kserve.io/v1alpha1
      - kind: Secret
        name: ngc-secret
        version: v1
      - kind: PersistentVolumeClaim
        name: nim-pvc
        version: v1
      - kind: ConfigMap
        name: nvidia-nim-data
        version: v1
      - kind: Secret
        name: nvidia-nim-secrets
        version: v1
      statusDescriptors:
      - displayName: Conditions
        path: conditions
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes.conditions
      version: v1alpha1
  description: ODH NIM Operator reconciles ODH NIM integration.
  displayName: ODH NIM Operator
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAAGAAAABgCAYAAADimHc4AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAAOpgAABdwnLpRPAAAAAZiS0dEAP8A/wD/oL2nkwAAAAlwSFlzAAAOxAAADsQBlSsOGwAAC4VJREFUeNrtnXtsVFUexz/3zqO0BesKdEstEfGB4WXQxcW4CEtkawK6yFoVXUOTjQqbDSTrH6ysQdcl6ppNWBP24W4iLhV8AImgpYhQXR9ABSryCEKhgCA1pW/ovO7j7B9npi2Fqe2dmXsK3G8ymTLMvb9zft855/x+v3N+v6vRA4QQAEFgLHA/MBW4ERgCZOGhK6JAA3AE2AqUAweAqKZpSS+66P/EFZ8NzAZmAXcCwwBddS8vEdjA98B2YA2wAQhfjIjzPokrHuSv/FmgBMhR3ZtLHCFgLfBn5OigKxEdf3VR/p3AcuA21S2/zFANPAXsgk4SdLhA+f/CU34mcBtSt5OgU+dal3/cBLwF3K66pZc5dgNzgBpN09C7LLh/xFO+G7gdqetsIUSHVfMr4CHVLbuCUAIUg1wDgsAvkaPAgzvIQZr4QR0Yh1x8PbiLacA4HZiJdLI8uIthwEwd+Dmeh6sCOjBVR3q9HtTgJk0IEcELrKlCVBNd3GAP7sOb+xXDI0AxPAIUwyNAMTwCFMMjQDEubQKEgFgMTFN1SxzDr7oBXSGam7GPHkVYFvqIEej5+ZDkRIFdW0v0tdew9u5FGzgQraAA3/jx+KdMwTdyJPj7VdeSot84YsaWLUSefx5r/34QAn3ECAIPPEDW3Lno119/3nftujpC8+ZhbNhw/k10Hb2oCP+UKQRmziQwdSpafr7qrvWIfkGAdegQ7SUlWPv2dWudhm/MGIKPPYZ/2jT0wYOxDh8mumwZxpYtcgpKhkAA3/jxBGfPJnDfffhuuQUCAdVdvQDKCRChEKEnnyS2alUPrdTQ8vLQcnMRLS2I9vY+9FBDLyiQo+Lee/EXF6MXFKjs8vnNU02AsWkT7SUliHPnMi/M78c3dixZTz1F8KGH0K65RmXXAdVWkG1jrFvnjvIBTBNrzx5CCxZwbtYsYmvXIsJhpSpQOgKsw4c5V1yMffy4ms7n5BB48EEGLF6Mb9QoJW1QOgLMrVuxT5xQJl+EQsRWriQ0dy7WwYNK2qCUAKu6umdLxiWYVVVEXnhByXSkjAD79GnMqipV4i+AsXEj1vbtrstVRoD5+edY33yjSvwFEG1tSqYhNQRYFsbGjWAYSsQnbdaRI67LVEKAVVOD+fHHKkT33K6dOxGtra7KVEKA+dFH2N9+q0J0j7AOHcI+dsxVma4TIMJhjE2b3Bbbu7Y1NWHt3euqTNcJOFNVRXjbNrfF9g62jbltm6umsesErC0v52RLS7/dCTJ37UI0N7smz1U9tLS08PaOHaxCphFqqd4wA7CPHXM1NJL+bSPTxG5sxK6txT5yBPvECez6enyWRWVbG7uqq/kayAd+E2+Ael+4E6K5GXPnTny3uZMmlzYCRH09xubNGBUVWF9/jX3ypIxy2jYgswI/CgYJR6OEgaVALvB44npXutubjgjM7dvJeuIJ0DM/QaRMgGhpIbZ6NdHXX5cWRBLnKgYci5MBcA54AbCAR5FpOvYPi3MF1t69iOZmtMGDMy4rJYrtmhraS0sJLVyItXt3z56tEOjdTi+cQWar/R6ZwdxfttHt2lrXwiSOCRD19YQWLMBYv75Xx0KygFsv8nk78CYyg3kLchSotpBEa2v/JyC6ciXGhx/2+vsaUCwEyc4o7EYuys8Dp5CjQRURAmhraHBlXXLUR9HQQOydd/rksFjIbMBZPXynGfg7cmFeBhyPN9BtIgzgk+pqoi4c+HLUN/vkSeza2j5f5wd+C/ykh+8I4CvkSCgB/gHU4R4ROtAIvPvVVzQdOuSKvD5DnDsHkUifr7OB64GXgJt/SAZQAywBHgT+AnwTv4cv/kq3I5e433rgi+PH+W7OHGIvvohdV5dmSV1kOtmUt6qrOTt9OqKpyZFQHTnnPwN82QflXAv8FBiNrBw1ChgYv5+NJM3JvK0hCW0FVgJ/A1p1nVV+P8WmCRMnEiwtJThnDlpenkNVJ5HthABRX8/Z6dNTihz6gf3AYuB/DhR3DZKIiUhSRgFDkSnoCXNWdHvv6HSXdxtoA/YB/wY2ItcANI2/ZmXxZCSCCRAIEJgxg+yXX07rCQpHprc2dCj+yZNTIsAExgCvIRfcMqRJ2ls0AZ/HX1nI0MZw5NQ2EiiMf3YVsgZDEDlSTCACtCDXln3IUXggTkQHhOBby+p0Dg0D4733EI2N5Cxfjm/8+LQQ4PhckFlVRfvs2dinT6fUAB3pJVcgyahCWkypQkcSMwCp/MSaYSN/4SFkkbeeZP1B03hGiAu+4xs9muyXXiJw//0pt9P5wSwhCC9ZQmTp0jSoSyroDPA28B9A3WkhiRzkqLyHi5OkFxWRu3o1/smTU5Lj3LLTNLLmz8c/aVJaOmwBg4HfAauQTtmP03JnZ5gM3EHy+JR96hSRV15Jee8gJdNaLyxkwLPPohcWpqXTIt7hsUizcy3wJ2QpFzcrB96MjE9dRc/GgVFRQeTVVzsivk6QlrOhsTffJLRwoWOzNBl88fdmpNm6AfgUGarIxIEWH/AzpBM4gd5FZ/VhwxhYXo5vwgRHMtMSgAw++igiHCa8aFFat/MSc28eci6eAnyHLD/4CbL84ElkaDuVULYP6SA+DvwaWZW2t4aAXVdHbN06sh0SkL7T0ZZFrKyM8OLFGfUcEyEJA2mKHkd6zC1IMmqRFVNbkWZtDGl6JrZAA8iNoMHAdcgI7Q3I8MjwuIy+KsQ/cSIDN21ylG+Q3uPpQmBs3kz46aexDhxI222TNh5JRsKxspGmZTvSzDwbf48hf9E60izNA64GBiFN1YR56nQUaUOGMKiyEt+4cX2+Nr17IJpGoLgYvaiI0IIFmJWVab19dwgunCoCwI+QnjJcPF4kurzS4XMQDjs+UZeRAKNvzBhy33iDAUuWoA9zvxpawpqykQru/krEjdIGXXecFpuxCK8+fDjZzz1H7po1+O++O2m+7+UAbdAgx/lmmQ2x6zr+u+4id/VqBixa1O9zdh13c/hwmVTu5FpXGnjttWQvXcrA998na/58V04buAn/tGloV1/t6Fr3k/QMA3PHDqL//CfGBx8gzp51VXy6oRUUMKi83PFBLvf3vQMB/JMnk7tiBbllZQSKi9FyLt1HFAQffhjfrbc6vl55orY4exZz2zaMigqMDRtk1mQKsRU3EbjnHnJWrEAvKnJ8D+UEdMC2sWtrMcrLib31FuaePRCNqm5VUug33EBuWRn+O1Or+tx/COgC0dCA+dlnxNavx6ysxD51ql+ksybgmzCBnGXL8E+ZkvK9+iUBHTBNrJoarC+/xDp4ELOyEuvgQfdKG3SDNnQoWaWlZM2bhz5yZHru2a8J6AbR2Ih14ADmF19gfvop1v792PX1smpWBqEXFhKYMYNgaSn+O+5IazGoS4qArhDhMOLUKTkydu6UR+KPHsX+/ntEW1tqZcz8fvT8fHxjx+KfOpXAjBn4Ro/OSBWuS5aACxCLyZJnp09j1dYiGhrAMBBNTdhnziCamqTPEYkg4uRogQDk5KDl5aEPGYJWWIiWk4Oen48+ejT6ddehZWf2uRaXDwE/BNsGywLb7nyCkaZ1BtIUxaquHAL6KVQfxb/i4RGgGB4BiuERoBgeAYrhEaAYOvIkhwc1iOjIx3B7UINGHXmwzIMa1OhAJf2nSsCVBBvYqiPTojJ3mNNDMtQBG3VkmpT7BTM9VAL7Eylaa5HnWD24g3bgXSCW8APWA2tUt+oKwhpkbRJ5eDgekb4RmSPnPVc+s9gNPAIc0TTtPE/4CDAv/gUPmUEVUscdJXo7toG67MtMApbjjYR0YzdS+bsgvhtHl1iQ1rkltwM5RP6LtzCnA+1IXT5CN+VDkoIj8dGQDfwCWaxkGlCAF7zrLWxkqtrHyHV1KxDWLrLv3ONOdJyIIDJ19z7k8+dvRCYSek/hPh8RZKmhGqTCNyJLUES1Hjb8/w+bHUpuhYx6lgAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMC0wMS0xMFQxNjo0Njo0NCswMDowMKzwOm4AAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjAtMDEtMTBUMTY6NDY6NDQrMDA6MDDdrYLSAAAARnRFWHRzb2Z0d2FyZQBJbWFnZU1hZ2ljayA2LjcuOC05IDIwMTktMDItMDEgUTE2IGh0dHA6Ly93d3cuaW1hZ2VtYWdpY2sub3JnQXviyAAAABh0RVh0VGh1bWI6OkRvY3VtZW50OjpQYWdlcwAxp/+7LwAAABh0RVh0VGh1bWI6OkltYWdlOjpoZWlnaHQANTEywNBQUQAAABd0RVh0VGh1bWI6OkltYWdlOjpXaWR0aAA1MTIcfAPcAAAAGXRFWHRUaHVtYjo6TWltZXR5cGUAaW1hZ2UvcG5nP7JWTgAAABd0RVh0VGh1bWI6Ok1UaW1lADE1Nzg2NzQ4MDTgzTkjAAAAE3RFWHRUaHVtYjo6U2l6ZQAxNS4xS0JCehw8bwAAAEJ0RVh0VGh1bWI6OlVSSQBmaWxlOi8vLi91cGxvYWRzLzU2LzhRdFpYUGgvMjEwOC9yZWRoYXRfaWNvbl8xMzA4NDQucG5n7pb6GgAAAABJRU5ErkJggg==
    mediatype: image/png
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - create
          - get
          - update
        - apiGroups:
          - nim.opendatahub.io
          resources:
          - odhnimaccounts
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - nim.opendatahub.io
          resources:
          - odhnimaccounts/finalizers
          verbs:
          - update
        - apiGroups:
          - nim.opendatahub.io
          resources:
          - odhnimaccounts/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - template.openshift.io
          resources:
          - templates
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: odh-nim-operator-sa
      deployments:
      - label:
          app.kubernetes.io/component: operator
          app.kubernetes.io/instance: odh-nim-operator-0.0.1
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: opendatahub-nim-operator
          app.kubernetes.io/part-of: opendatahub-nim-operator
          app.kubernetes.io/version: 0.0.1
        name: odh-nim-operator-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              app.kubernetes.io/component: operator
              app.kubernetes.io/part-of: opendatahub-nim-operator
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                app.kubernetes.io/component: operator
                app.kubernetes.io/instance: odh-nim-operator-0.0.1
                app.kubernetes.io/managed-by: kustomize
                app.kubernetes.io/name: opendatahub-nim-operator
                app.kubernetes.io/part-of: opendatahub-nim-operator
                app.kubernetes.io/version: 0.0.1
            spec:
              containers:
              - args:
                - --leader-elect
                - --probe-address=:8081
                - --metric-address=127.0.0.1:8080
                - --debug
                - --enable-webhooks
                image: quay.io/ecosystem-appeng/odh-nim-operator:0.0.1
                imagePullPolicy: IfNotPresent
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                ports:
                - containerPort: 9443
                  name: webhook-server
                  protocol: TCP
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
                volumeMounts:
                - mountPath: /tmp/k8s-webhook-server/serving-certs
                  name: cert
                  readOnly: true
              - args:
                - --secure-listen-address=0.0.0.0:8383
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.14.1
                imagePullPolicy: IfNotPresent
                name: kube-rbac-proxy
                ports:
                - containerPort: 8383
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: odh-nim-operator-sa
              volumes:
              - name: cert
                secret:
                  defaultMode: 420
                  secretName: webhook-server-cert
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - openshift ai
  - nvidia nim
  links:
  - name: Odh Nim Operator
    url: https://github.com/RHEcosystemappeng/odh-nim-operator
  maintainers:
  - email: tfigenbl@redhat.com
    name: Tomer Figenblat
  - email: xiezhang@redhat.com
    name: Xieshen Zhang
  maturity: alpha
  minKubeVersion: 1.29.0
  provider:
    name: Red Hat
    url: https://www.redhat.com
  version: 0.0.1
  webhookdefinitions:
  - admissionReviewVersions:
    - v1
    containerPort: 443
    deploymentName: odh-nim-operator-manager
    failurePolicy: Fail
    generateName: validate.nim.opendatahub.io.v1alpha1.odhnimaccount
    rules:
    - apiGroups:
      - nim.opendatahub.io
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      - DELETE
      resources:
      - odhnimaccounts
    sideEffects: None
    targetPort: 9443
    type: ValidatingAdmissionWebhook
    webhookPath: /validate-nim-opendatahub-io-v1alpha1-odhnimaccount
