---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-nim-opendatahub-io-v1alpha1-odhnimaccount
  failurePolicy: Fail
  name: validate.nim.opendatahub.io.v1alpha1.odhnimaccount
  rules:
  - apiGroups:
    - nim.opendatahub.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - odhnimaccounts
  sideEffects: None
