apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - path: deployment_ca_secret.yaml
  - path: openshift_ca_injection.yaml
  - target:
      kind: Deployment
    patch: |
      - op: test
        path: /spec/template/spec/containers/0/name
        value: manager
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --enable-webhooks
